Make local GitLab accessible via http://gitlab.localdev

diff --git a/local-cluster/lib/environment b/local-cluster/lib/environment
--- a/local-cluster/lib/environment
+++ b/local-cluster/lib/environment
@@ -1,6 +1,15 @@
 #!/usr/bin/env bash -e
+[ ! -f ${configdir}/vars.yml ] && \
+    echo "ERROR: ${configdir}/vars.yml does not exist!" && \
+    exit 1
+
+export local_gitlab_fqdn=$(grep "gitlab_fqdn:" "${configdir}/vars.yml" | sed "s/gitlab_fqdn: *//g")
+
 export local_gitlab_ip='192.168.246.10'
 export local_runner_ip='192.168.246.11'
 
-export local_cluster_ssh_config_marker_start="=== CICD_LOCAL_CLUSTER_SSH_CONFIG_BEGIN ==="
-export local_cluster_ssh_config_marker_end="=== CICD_LOCAL_CLUSTER_SSH_CONFIG_END ==="
+export local_cluster_ssh_config_marker_start="# === CICD_LOCAL_CLUSTER_SSH_CONFIG_BEGIN ==="
+export local_cluster_ssh_config_marker_end="# === CICD_LOCAL_CLUSTER_SSH_CONFIG_END ==="
+
+export local_cluster_etc_hosts_marker_start="# === CICD_LOCAL_CLUSTER_HOSTS_BEGIN ==="
+export local_cluster_etc_hosts_marker_end="# ===  CICD_LOCAL_CLUSTER_HOSTS_END  ==="
diff --git a/scripts/configure b/scripts/configure
--- a/scripts/configure
+++ b/scripts/configure
@@ -11,19 +11,27 @@
 configdir="$(scripts/get_abspath $configdir)"
 echo "Cluster configdir is at ${configdir}"
 
-get_inventory_hook=${configdir}/hooks/get-inventory
-echo "Looking for inventory script at ${get_inventory_hook}"
-[ ! -x "${get_inventory_hook}" ] && \
-    echo "ERROR: ${get_inventory_hook} does not exist" && \
+hook=${configdir}/hooks/pre-configure
+[ ! -e "${hook}" ] && \
+    echo "ERROR: Hook ${hook} does not exist." && \
     exit 1
-# NOTE: The hook may return a comma-delimited string of hostnames/IPs
-#       OR a path to an inventory file. Ansible accepts either.
-inventory=$($get_inventory_hook)
+
+[ ! -x "${hook}" ] && \
+    echo "ERROR: Hook ${hook} exists but is not executable." && \
+    exit 1
+
+source $hook
+
+[ -z "${inventory}" ] && \
+    echo "ERROR: \$inventory was not defined by hook ${hook}" && \
+    exit 1
 
 cd configurator
 set -x
 
-ansible-playbook --inventory ${inventory} \
+ansible-playbook \
+    --inventory ${inventory} \
+    --extra-vars "@${configdir}/vars.yml" \
     gitlab.yml
 
 { set +x; } 2>/dev/null
